### ISSUE TITLE
Does not work for Firefox

### ISSUE THREAD

**Issue by j4cknife** [lenovo-inc/superfishremoval#13]
I've acquired the cert via the following github project: https://gist.github.com/mathiasbynens/7a13a467b22c42505490

I added the cert to firefox's certs and the lennovo tool does not remove it from firefox's certificates. It does work when added to certmgr in windows.

tested on windows 8.1 firefox 35.0.1

**Comment by David-Allison** [comment]
When superfish.pem is added to Firefox. It is listed by certutil.exe as "Superfish, Inc. - Superfish, Inc.".

[MozillaCertificateUtility#145](https://github.com/lenovo-inc/superfishremoval/blob/master/SuperFishRemovalTool/Utilities/MozillaCertificateUtility.cs#L145) searches for a certificate named "Superfish, Inc.", this match fails, therefore the certificate is not found or removed.

**Comment by lenovo-inc** [comment]
Thanks for looking into this.  This utility *does* remove the certificate that is added to Firefox by the version(s) of Superfish that were peloaded on some Lenovo devices.  However, we will look into reproducing this test case and making necessary adjustments
