### ISSUE TITLE
Add NSS binary info in the main README

### ISSUE THREAD

**Issue by Alcesmire** [lenovo-inc/superfishremoval#3]
Consider adding some mentions about the NSS binaries in the main README, and not only in the NSS directory. Also consider mentioning where people can find the source of those packages as well. Bundling binaries in a repo ***made to show transparency and harmlessness of your application*** is not a good thing and any such inclusion should come with very good, public and explicit reasoning. Binaries can be easily tampered with unnoticed, sources cannot.

**Comment by lenovo-inc** [comment]
Thanks for the suggestion!
