### ISSUE TITLE
Localisation: Resources.resx

### ISSUE THREAD

**Issue by David-Allison** [lenovo-inc/superfishremoval#5]
The project uses a custom string localisation scheme instead of the Project Resources (Resources.resx) solution.

Is there a rationale behind this?

**Comment by lenovo-inc** [comment]
With commit 65094ee8ddf0c17b01ed64f5c86c7b94b4f6bbb9 we moved the string localization into a separate XML file, providing the capability to add more languages in the future.

This is still quite far from the normal way of doing localization, but the primary goal is to avoid satellite assemblies or multiple build stages (for transforming .resx into .resource).

**Comment by kam123b** [comment]
> The project uses a custom string localisation scheme instead of the Project Resources (Resources.resx) solution.
> 
> Is there a rationale behind this?
