### ISSUE TITLE
[Discussion] Logging Libraries

### ISSUE THREAD

**Issue by David-Allison** [lenovo-inc/superfishremoval#7]
Are there any preferences as to the logging library that should be used for this project?

I'd personally use log4net, but would be interested to hear the opinions of Lenovo staff on the matter.

**Comment by johnduhart** [comment]
Seriously, relax. This is a one off tool, not your next enterprise SOA project.

Consider spending time contributing to [some other C# project](https://github.com/trending?l=csharp).

**Comment by war59312** [comment]
John, that is a piss poor attitude to have.

If someone, David, whishes to contiribute then he should be able to, without others (you) scolding him.

He is willing to give his time and engery to give back. For free! I do not take that lightly.

David, I for one appericate everything. So, thank you Sir!

**Comment by lenovo-inc** [comment]
The goal was to have a standalone executable without other dependencies.  Being dependent on the NSS library lessened that ability, but we would still like to keep to that goal.  We also have the concern of leaving behind a presence after running (including log files). We will look into this, possibly having a static facade Logger class with an implementation that writes to console or a temporary text file.
